target-version = "py313"

line-length = 88

[format]
quote-style = "double"

[lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]

[lint.pydocstyle]
convention = "google"

[lint.pycodestyle]
max-doc-length = 88
